{% set name = "perl-data-dumper-concise" %}
{% set version = "2.023" %}
{% set sha256 = "a6c22f113caf31137590def1b7028a7e718eface3228272d0672c25e035d5853" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/E/ET/ETHER/Data-Dumper-Concise-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    weak:
      - {{ name }} ={{ version }}

requirements:
  host:
    - perl =>5.32
    - make  # [not win]
    - m2-make  # [win]

  run:
    - perl =>5.32

test:
  # Perl 'use' tests
  imports:
    - Data::Dumper::Concise
    - Data::Dumper::Concise::Sugar



about:
  home: http://metacpan.org/pod/Data-Dumper-Concise
  license: perl_5
  summary: 'Less indentation and newlines plus sub deparsing'

extra:
  recipe-maintainers:
    - khaled196
