{% set name = "perl-date-calc" %}
{% set version = "6.4" %}
{% set sha256 = "7ce137b2e797b7c0901f3adf1a05a19343356cd1f04676aa1c56a9f624f859ad" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/S/ST/STBEY/Date-Calc-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    weak:
      - {{ name }} ={{ version }}
  skip: true  # [win]

requirements:
  host:
    - perl =>5.32
    - perl-carp-clan
    - perl-bit-vector
    - make  # [not win]

  run:
    - perl =>5.32
    - perl-carp-clan
    - perl-bit-vector

test:
  # Perl 'use' tests
  imports:
    - Date::Calc
    - Date::Calc::Object
    - Date::Calc::PP
    - Date::Calendar
    - Date::Calendar::Profiles
    - Date::Calendar::Year


about:
  home: http://metacpan.org/pod/Date-Calc
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1
  summary: 'Gregorian calendar date calculations'

extra:
  recipe-maintainers:
    - khaled196
