{% set name = "perl-text-unidecode" %}
{% set version = "1.30" %}
{% set sha256 = "6c24f14ddc1d20e26161c207b73ca184eed2ef57f08b5fb2ee196e6e2e88b1c6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/S/SB/SBURKE/Text-Unidecode-{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  number: 0
  run_exports:
    weak:
      - {{ name }} ={{ version }}
  skip: true  # [win]

requirements:
  host:
    - make  # [not win]
    - perl =>5.32  
  run:
    - perl =>5.32

test:
  imports:
    - Text::Unidecode



about:
  home: http://metacpan.org/pod/Text-Unidecode
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1
  summary: 'Provide plain ASCII transliterations of Unicode text'

extra:
  recipe-maintainers:
    - khaled196
