{% set name = "perl-mojolicious" %}
{% set version = "9.33" %}
{% set sha256 = "1477f33f777a2f167d0e19cda1ad7782d296c21b2b9cd04f8b49ea706a7c2f3b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/mojolicious/mojo/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    weak:
      - {{ name }} ={{ version }}

requirements:
  host:
    - perl =>5.32
    - make  # [not win]
    - m2-make  # [win]

  run:
    - perl =>5.32

test:
  # Perl 'use' tests
  imports:
    - Mojolicious
    - Mojolicious::Command
    - Mojolicious::Command::Author::cpanify
    - Mojolicious::Command::Author::generate
    - Mojolicious::Command::Author::generate::app
    - Mojolicious::Command::Author::generate::dockerfile
    - Mojolicious::Command::Author::generate::lite_app
    - Mojolicious::Command::Author::generate::makefile
    - Mojolicious::Command::Author::generate::plugin
    - Mojolicious::Command::Author::inflate
    - Mojolicious::Command::cgi
    - Mojolicious::Command::daemon
    - Mojolicious::Command::eval
    - Mojolicious::Command::get
    - Mojolicious::Command::prefork
    - Mojolicious::Command::psgi
    - Mojolicious::Command::routes
    - Mojolicious::Command::version
    - Mojolicious::Commands
    - Mojolicious::Controller
    - Mojolicious::Lite
    - Mojolicious::Plugin
    - Mojolicious::Plugin::Config
    - Mojolicious::Plugin::DefaultHelpers
    - Mojolicious::Plugin::EPLRenderer
    - Mojolicious::Plugin::EPRenderer
    - Mojolicious::Plugin::HeaderCondition
    - Mojolicious::Plugin::JSONConfig
    - Mojolicious::Plugin::Mount
    - Mojolicious::Plugin::NotYAMLConfig
    - Mojolicious::Plugin::TagHelpers
    - Mojolicious::Plugins
    - Mojolicious::Renderer
    - Mojolicious::Routes
    - Mojolicious::Routes::Match
    - Mojolicious::Routes::Pattern
    - Mojolicious::Routes::Route
    - Mojolicious::Sessions
    - Mojolicious::Static
    - Mojolicious::Types
    - Mojolicious::Validator
    - Mojolicious::Validator::Validation


about:
  home: https://mojolicious.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Real-time web framework'
extra:
  recipe-maintainers:
    - khaled196
