{% set name = "perl-data-structure-util" %}
{% set version = "0.16" %}
{% set sha256 = "9cd42a13e65cb15f3a76296eb9a134da220168ec747c568d331a50ae7a2ddbc6" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/A/AN/ANDYA/Data-Structure-Util-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    weak:
      - {{ name }} ={{ version }}
  missing_dso_whitelist:
    - /lib64/libc.so.6
  skip: true  # [win]
  skip: true  # [osx]

requirements:
  host:
    - make  # [not win]
    - {{ compiler('c') }}
    - perl =>5.32   
  run:
    - perl =>5.32

test:
  # Perl 'use' tests
  imports:
    - Data::Structure::Util

about:
  home: http://metacpan.org/pod/Data-Structure-Util
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1
  summary: 'Change nature of data within a structure'

extra:
  recipe-maintainers:
    - khaled196
